package org.ndot.ws;
//Generated by MyEclipse

public class Books_wsImpl implements IBooks_ws {
	
	public String getBooks() {
		StringBuffer books = new StringBuffer();
		books.append("<?xml version=\"1.0\" encoding=\"utf-8\"?><books>");
		books
				.append("<book><bookId>001</bookId><name>java基础教程</name><author>NDot</author><price>78.00</price></book>");
		books
				.append("<book><bookId>002</bookId><name>Flex基础教程</name><author>SJC</author><price>68.00</price></book>");
		books
				.append("<book><bookId>003</bookId><name>WS基础教程</name><author>PanPan</author><price>88.00</price></book>");
		books.append("</books>");
		return books.toString();
	}
	
}