---业务机构人员树
CREATE VIEW VIEW_ORGAN_USER  AS
SELECT ORGAN_NO,ORGAN_NAME, ORGAN_LEVEL,ORGAN_PATH,PARENT_ORGAN,FLAG  FROM  (
SELECT  aa.ORGAN_NO,aa.ORGAN_NAME ,aa.ORGAN_LEVEL,aa.ORGAN_PATH,aa.PARENT_ORGAN,'1' FLAG  FROM SM_ORGAN aa  WHERE aa.ORGAN_TYPE='0'

UNION

SELECT  bb.USER_NO,bb.USER_NAME,bb.USER_STATE,oo.ORGAN_PATH ,bb.ORGAN_NO,'2' FLAG  FROM   SM_USERS bb,SM_ORGAN oo WHERE oo.ORGAN_NO=bb.ORGAN_NO AND oo.ORGAN_TYPE='0'

 ) tt
ORDER by  tt.ORGAN_PATH,FLAG